# Generated by Django 4.2.2 on 2023-06-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bot_state',
            field=models.CharField(blank=True, help_text='Стейт машина', max_length=50, null=True, verbose_name='Текущее состояние бота'),
        ),
    ]
