# Generated by Django 4.2.2 on 2023-06-20 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='about_me',
            field=models.CharField(blank=True, help_text='Расскажи ещё немного о себе (хобби, пет-проекты и т.д.)', max_length=250, verbose_name='Информация о пользователе'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время публикации анкеты'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ready_to_chat',
            field=models.BooleanField(db_index=True, default=False, help_text='Заполнена ли анкета?', verbose_name='Готовность общаться'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='real_name',
            field=models.CharField(blank=True, help_text='Как к тебе могут обращаться другие участники?', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='topics',
            field=models.CharField(blank=True, help_text='О чем бы ты хотел пообщаться?', max_length=150, verbose_name='Предпочитаемые темы для общения'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='work_place',
            field=models.CharField(blank=True, help_text='Где и кем ты работаешь?', max_length=100, verbose_name='Место работы и должность'),
        ),
    ]
