# Generated by Django 4.2.2 on 2023-06-23 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='polls',
            field=models.ManyToManyField(to='polls.poll', verbose_name='опросы'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'менеджер'), ('guest', 'гость'), ('speaker', 'спикер')], max_length=30, verbose_name='роль'),
        ),
    ]
