# Generated by Django 4.2.2 on 2023-06-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'менеджер'), ('guest', 'гость'), ('speaker', 'спикер')], max_length=30, verbose_name='роль'),
        ),
    ]
