# Generated by Django 4.2.2 on 2023-06-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_bot_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_subscriber',
            field=models.BooleanField(default=True, verbose_name='подписчик'),
        ),
    ]
