# Generated by Django 4.2.2 on 2023-06-21 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_about_me_customuser_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(blank=True, help_text='Из какого ты города?', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stack',
            field=models.CharField(blank=True, help_text='Твой стек. Какие технологии используешь в работе?', max_length=150, verbose_name='Стек технологий'),
        ),
    ]
