# Generated by Django 4.2.2 on 2023-06-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city_customuser_stack'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bot_state',
            field=models.CharField(blank=True, help_text='Стейт машина', max_length=50, verbose_name='Текущее состояния бота'),
        ),
    ]
