# Generated by Django 4.2.2 on 2023-06-22 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='role',
            field=models.CharField(blank=True, choices=[('manager', 'менеджер'), ('guest', 'гость'), ('speaker', 'спикер')], default='guest', max_length=30, verbose_name='роль'),
        ),
    ]
