# Generated by Django 4.2.2 on 2023-06-22 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_person_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='questioned_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата'),
            preserve_default=False,
        ),
    ]
