# Generated by Django 4.2.2 on 2023-06-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_question_questioned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='последние изменения'),
        ),
    ]
