# Generated by Django 4.2.2 on 2023-06-22 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_report_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='последние изменения'),
        ),
    ]
