# Generated by Django 4.2.2 on 2023-06-22 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='about_me',
            field=models.CharField(blank=True, help_text='Расскажи ещё немного о себе (хобби, пет-проекты и т.д.)', max_length=250, verbose_name='Информация о пользователе'),
        ),
        migrations.AddField(
            model_name='person',
            name='city',
            field=models.CharField(blank=True, help_text='Из какого города?', max_length=50, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='person',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата и время публикации анкеты'),
        ),
        migrations.AddField(
            model_name='person',
            name='ready_to_chat',
            field=models.BooleanField(db_index=True, default=False, help_text='Анкета заполнена?', verbose_name='Готовность общаться'),
        ),
        migrations.AddField(
            model_name='person',
            name='real_name',
            field=models.CharField(blank=True, help_text='Как к тебе могут обращаться другие участники?', max_length=50, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='person',
            name='stack',
            field=models.CharField(blank=True, help_text='Твой стек. Какие технологии используешь в работе?', max_length=150, verbose_name='Стек технологий'),
        ),
        migrations.AddField(
            model_name='person',
            name='topics',
            field=models.CharField(blank=True, help_text='О чем хочешь пообщаться?', max_length=150, verbose_name='Предпочитаемые темы для общения'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_place',
            field=models.CharField(blank=True, help_text='Где и кем ты работаешь?', max_length=100, verbose_name='Место работы и должность'),
        ),
        migrations.AlterField(
            model_name='person',
            name='bot_state',
            field=models.IntegerField(blank=True, default=0, help_text='номер стейта', verbose_name='Статус бота'),
        ),
    ]
