# Generated by Django 4.2.2 on 2023-06-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='имя')),
                ('city', models.CharField(max_length=255, verbose_name='город')),
                ('job', models.CharField(max_length=255, verbose_name='работа')),
                ('stack', models.CharField(max_length=255, verbose_name='стек')),
                ('topics', models.TextField(verbose_name='темы')),
                ('about', models.TextField(verbose_name='о себе')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='дата изменения')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
            ],
            options={
                'verbose_name': 'анкета',
                'verbose_name_plural': 'анкеты',
            },
        ),
    ]
