# Generated by Django 4.2.2 on 2023-06-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_poll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='topics',
            field=models.TextField(verbose_name='интересы'),
        ),
    ]
